services:
  fntv-record-view:
    container_name: fntv-record-view
    image: qiaokes/fntv-record-view:latest
    ports:
      - "5000:5000"
    volumes:
      # 只读挂载外部数据库目录到容器内的database目录
      - /usr/local/apps/@appdata/trim.media/database:/app/database:ro
      # 挂载日志文件（可写）
      - ./app.log:/app/app.log
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    network_mode: bridge
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1.0'
        reservations:
          memory: 50M
          cpus: '0.5'